# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 09:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('website', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('phone_open_time', models.TimeField(blank=True, null=True)),
                ('phone_close_time', models.TimeField(blank=True, null=True)),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('city', models.TextField()),
                ('state', models.TextField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('description', models.TextField()),
                ('children_allowed', models.BooleanField()),
                ('male_only', models.BooleanField()),
                ('female_only', models.BooleanField()),
                ('lgbt_focus', models.BooleanField()),
                ('mental_disability_focus', models.BooleanField()),
                ('physical_disability_focus', models.BooleanField()),
                ('veteran_focus', models.BooleanField()),
                ('pets_allowed', models.BooleanField()),
                ('drug_free', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrimarySecondaryNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('big_image', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('facilities', models.ManyToManyField(to='resource_finder.Facility')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_finder.Facility'),
        ),
    ]
