# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_finder', '0003_auto_20161016_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='phone_close_time',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='phone_open_time',
            new_name='open_time',
        ),
    ]
